"""assets/docs/manifest*.json + assets/proto/*.webp → assets/js/docs.js
manifest.json(기본) 위에 manifest-joseon.json, manifest-personal.json 항목을 slug 기준으로 덮어씁니다."""
import json, os, glob
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
KEYS = ("slug", "title", "pages", "pageCount", "sourcePages", "updated", "summary", "points", "pageNotes", "url")
by = {}
for name in ("manifest.json", "manifest-joseon.json", "manifest-personal.json"):
    f = os.path.join(root, "assets/docs", name)
    if not os.path.exists(f): continue
    for d in json.load(open(f, encoding="utf-8")):
        if d.get("slug", "").startswith("castle"): continue
        cur = by.get(d["slug"], {})
        cur.update({k: d[k] for k in KEYS if k in d and d[k] not in (None, "")})
        # keep previous pages if the newer entry could not be downloaded
        if not d.get("pages") and by.get(d["slug"], {}).get("pages"): cur["pages"] = by[d["slug"]]["pages"]
        by[d["slug"]] = cur
# drop page files that no longer exist on disk
for d in by.values():
    d["pages"] = [p for p in d.get("pages", []) if os.path.exists(os.path.join(root, "assets/docs", d["slug"], p))]
docs = [d for d in by.values() if d.get("pages") or d.get("summary")]
caps = {"inventory-03": "AI로 만든 UI 목업 · 의식판(인벤토리) 화면", "inventory-01": "목업 · 전투 HUD", "inventory-02": "목업 · 전체 화면", "inventory-04": "목업 · 설정 메뉴"}
order = ["inventory-03", "inventory-01", "inventory-02", "inventory-04"]
proto = [[f"assets/proto/{os.path.basename(p)}", caps.get(os.path.basename(p)[:-5], "AI UI 목업")] for p in sorted(glob.glob(os.path.join(root, "assets/proto/*.webp")), key=lambda p: order.index(os.path.basename(p)[:-5]) if os.path.basename(p)[:-5] in order else 99)]
with open(os.path.join(root, "assets/js/docs.js"), "w", encoding="utf-8") as f:
    f.write("/* generated by tools/build_docs.py — do not edit */\n")
    f.write("window.DOCS = " + json.dumps(docs, ensure_ascii=False) + ";\n")
    f.write("window.PROTO_SHOTS = " + json.dumps(proto, ensure_ascii=False) + ";\n")
print(len(docs), "docs,", len(proto), "proto shots")
