"""assets/docs/manifest.json + assets/proto/*.webp → assets/js/docs.js"""
import json, os, glob
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
m = json.load(open(os.path.join(root, "assets/docs/manifest.json"), encoding="utf-8"))
docs = [{k: d.get(k) for k in ("slug", "title", "pages", "pageCount")} for d in m if d.get("pages")]
caps = {"inventory-03": "AI로 만든 UI 목업 · 의식판(인벤토리) 화면", "inventory-01": "목업 · 전투 HUD", "inventory-02": "목업 · 전체 화면", "inventory-04": "목업 · 설정 메뉴"}
order = ["inventory-03", "inventory-01", "inventory-02", "inventory-04"]
proto = [[f"assets/proto/{os.path.basename(p)}", caps.get(os.path.basename(p)[:-5], "AI UI 목업")] for p in sorted(glob.glob(os.path.join(root, "assets/proto/*.webp")), key=lambda p: order.index(os.path.basename(p)[:-5]) if os.path.basename(p)[:-5] in order else 99)]
with open(os.path.join(root, "assets/js/docs.js"), "w", encoding="utf-8") as f:
    f.write("/* generated by tools/build_docs.py — do not edit */\n")
    f.write("window.DOCS = " + json.dumps(docs, ensure_ascii=False) + ";\n")
    f.write("window.PROTO_SHOTS = " + json.dumps(proto, ensure_ascii=False) + ";\n")
print(len(docs), "docs,", len(proto), "proto shots")
